// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFQBY78tTumnhmc_7h_6y2su-gyRKY9WA',
    appId: '1:1096348049483:web:7bcc68806340dbe1ee2dce',
    messagingSenderId: '1096348049483',
    projectId: 'taller-base-2a5cd',
    authDomain: 'taller-base-2a5cd.firebaseapp.com',
    storageBucket: 'taller-base-2a5cd.firebasestorage.app',
    measurementId: 'G-VQ2TJZVN7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAudpdPm4llQFkD2ETWey5mnTsg96F2Xls',
    appId: '1:1096348049483:android:ff1af4386b76c751ee2dce',
    messagingSenderId: '1096348049483',
    projectId: 'taller-base-2a5cd',
    storageBucket: 'taller-base-2a5cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuF8yTT4OaB5wE3C2yFd7QwIZ3PrmBRdk',
    appId: '1:1096348049483:ios:81beb0a744f72a15ee2dce',
    messagingSenderId: '1096348049483',
    projectId: 'taller-base-2a5cd',
    storageBucket: 'taller-base-2a5cd.firebasestorage.app',
    iosBundleId: 'com.example.ucevaflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuF8yTT4OaB5wE3C2yFd7QwIZ3PrmBRdk',
    appId: '1:1096348049483:ios:81beb0a744f72a15ee2dce',
    messagingSenderId: '1096348049483',
    projectId: 'taller-base-2a5cd',
    storageBucket: 'taller-base-2a5cd.firebasestorage.app',
    iosBundleId: 'com.example.ucevaflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFQBY78tTumnhmc_7h_6y2su-gyRKY9WA',
    appId: '1:1096348049483:web:7130eed5c0a55201ee2dce',
    messagingSenderId: '1096348049483',
    projectId: 'taller-base-2a5cd',
    authDomain: 'taller-base-2a5cd.firebaseapp.com',
    storageBucket: 'taller-base-2a5cd.firebasestorage.app',
    measurementId: 'G-GZZ8S4GDGF',
  );

}